### ISSUE TITLE
Task: Implement the front-end for viewing the employees at a building. 

### ISSUE THREAD

**Issue by IsabelleCzuboka** [amczuboka/Decagon-CondoManagementSystem#117]
This is about adding a button like "view employees" when clicking on a building as a manager to view. This is the same page that will also have a button for viewing the units. This also includes the page that will list the employees when clicking on the button.

**Comment by IsabelleCzuboka** [comment]
#54

**Comment by amczuboka** [comment]
Will not be implemented, will only  keep the #119
