### ISSUE TITLE
Task: Create prototype UIs for some pages in Sprint 3

### ISSUE THREAD

**Issue by IsabelleCzuboka** [amczuboka/Decagon-CondoManagementSystem#131]
You can use Figma or you can hardcode it already. These are some of the pages you can do: .

**Comment by IsabelleCzuboka** [comment]
#10

**Comment by KarinaSandur** [comment]
UI Prototypes for Sprint 3 have been uploaded and can be seen in the 'documentation/UI_Prototype' folder.
