### ISSUE TITLE
User Story 15: As a condo owner or renter, I would like to submit requests so I can easily be catered to.

### ISSUE THREAD

**Issue by amczuboka** [amczuboka/Decagon-CondoManagementSystem#34]
Task Breakdown:

Task A: Implement front-end for Request page.
Task B: Implement back-end for Request page.
Task C: Implement front-end for Assignments page. 
Task D: Implement back-end for Assignments page.
Task 5: Create acceptance test for Request page.
Task: Create acceptance test for Assignments page.

**Comment by IsabelleCzuboka** [comment]
all issues closed
