### ISSUE TITLE
User Story 19: As a condo manager, I would like to view a simplified financial system to easily generate important information.

### ISSUE THREAD

**Issue by amczuboka** [amczuboka/Decagon-CondoManagementSystem#61]
Task Breakdown: 

Task A: Implement front-end for "Budget Report" page.
Task B: Implement back-end for "Budget Report" page.
Task C: Implement front-end for "Add New Building Operation" page.
Task D: Implement back-end for "Add New Building Operation" page.
Task E: Create user acceptance for "Budget Report" page.
Task F: Create user acceptance test for "Add New Building Operation" page.

**Comment by IsabelleCzuboka** [comment]
all issues closed
