### ISSUE TITLE
Task: Create prototype UI's for some pages in Sprint 2.

### ISSUE THREAD

**Issue by IsabelleCzuboka** [amczuboka/Decagon-CondoManagementSystem#99]
You can use Figma to design the following pages that we will be coding in Sprint 2. Or you can already code it out. The following pages that we will be doing in Sprint 2 are: 
- Landing page
- Property dashboard
- Page where manager can see employees details and change their role. (when looking at the details of a building, should be a button that says view employees as well as view units).
- Page where they create a profile for a building. This is a form the manager fills out. 
-  Page where they create a profile for a unit. (The information is similar for unit, parking and storage). Maybe the pages change a little. This is a form the manager fills out.

**Comment by IsabelleCzuboka** [comment]
#10

**Comment by KarinaSandur** [comment]
PR merged!
